# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: orchestrator.proto for package 'orchestrator'

require "grpc"
require_relative "./orchestrator_pb"

module Orchestrator
  module OrchestratorService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "orchestrator.OrchestratorService"

      rpc :TriggerPlaylist, ::Orchestrator::PlaylistRequest, ::Orchestrator::PlaylistResponse
      rpc :SeguePlaylist, ::Orchestrator::PlaylistSegue, ::Orchestrator::PlaylistSegueResponse
    end

    Stub = Service.rpc_stub_class
  end
end
