# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wiphala.proto

require "google/protobuf"


descriptor_data = "\n\rwiphala.proto\x12\x07wiphala\"?\n\x0eTriggerRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\"/\n\x0fTriggerResponse\x12\x0c\n\x04slug\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"?\n\x0cSegueRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\" \n\rSegueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x86\x01\n\x0eWiphalaService\x12<\n\x07Trigger\x12\x17.wiphala.TriggerRequest\x1a\x18.wiphala.TriggerResponse\x12\x36\n\x05Segue\x12\x15.wiphala.SegueRequest\x1a\x16.wiphala.SegueResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Wiphala
  TriggerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wiphala.TriggerRequest").msgclass
  TriggerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wiphala.TriggerResponse").msgclass
  SegueRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wiphala.SegueRequest").msgclass
  SegueResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wiphala.SegueResponse").msgclass
end
