# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: wiphala.proto for package 'wiphala'

require "grpc"
require_relative "wiphala_pb"

module Wiphala
  module WiphalaService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "wiphala.WiphalaService"

      rpc :Trigger, ::Wiphala::TriggerRequest, ::Wiphala::TriggerResponse
      rpc :Segue, ::Wiphala::SegueRequest, ::Wiphala::SegueResponse
    end

    Stub = Service.rpc_stub_class
  end
end
